import resumakerIcon from './assets/resumaker-icon.svg'
import './App.css'

const sections = [
  {
    id: 'service',
    title: 'The Service',
    body: [
      {
        type: 'p',
        text: 'Resumaker detects job postings on the active browser tab and uses information you provide in your profile to generate a tailored resume via an AI model. Resumaker is provided as-is and may be changed, limited, or discontinued at any time.',
      },
    ],
  },
  {
    id: 'eligibility',
    title: 'Eligibility',
    body: [
      {
        type: 'p',
        text: 'You must be at least 13 years old to use Resumaker. By using the extension, you confirm you meet this requirement and that the information in your profile is accurate and belongs to you.',
      },
    ],
  },
  {
    id: 'account',
    title: 'Your Account',
    body: [
      {
        type: 'p',
        text: 'You sign in via Google, LinkedIn, or email. You are responsible for maintaining the security of your account and for all activity under it. Notify us immediately if you suspect unauthorized access.',
      },
    ],
  },
  {
    id: 'billing',
    title: 'Subscription Plans and Billing',
    body: [
      {
        type: 'ul',
        items: [
          'Free plan — a limited number of resume generations at no cost, as described in the extension.',
          'Plus and Pro plans — paid monthly subscriptions that include a higher (Pro: high-volume, marketed as unlimited but subject to a fair-use monthly cap) number of resume generations and additional features, as described on our pricing page at the time of purchase.',
          'Payments are processed securely by Stripe; Resumaker is the seller of record for your subscription. Card details are handled by Stripe, not stored by us. By subscribing you also agree to any applicable Stripe terms presented at checkout.',
          'Subscriptions renew automatically each month until canceled. You can cancel anytime through the billing portal accessible from within the extension; you will retain access through the end of the period you already paid for.',
          'Monthly generation quotas do not roll over or stack — unused generations are forfeited at the end of each billing period or refill window.',
          'Refunds are handled on a case-by-case basis. Contact us at the email below to request one.',
          "We may change pricing or plan features going forward; changes will not apply retroactively to a period you've already paid for.",
        ],
      },
    ],
  },
  {
    id: 'ai-content',
    title: 'AI-Generated Content',
    body: [
      {
        type: 'p',
        text: 'Resumes are generated by an AI model based on the information in your profile and the job posting you select. You are solely responsible for reviewing every generated resume for accuracy before using it — checking dates, titles, claims, and any other details — before submitting it to an employer. Resumaker does not guarantee that generated content is error-free, that it will result in an interview or job offer, or that it is suitable for every employer’s requirements or applicant tracking system.',
      },
    ],
  },
  {
    id: 'acceptable-use',
    title: 'Acceptable Use',
    body: [
      { type: 'p', text: 'You agree not to:' },
      {
        type: 'ul',
        items: [
          'Use Resumaker to generate a resume containing information you know to be false about yourself.',
          "Use another person's identity or profile without their consent.",
          'Attempt to circumvent usage quotas, tier restrictions, or payment requirements.',
          'Reverse-engineer, scrape, or interfere with the extension, our servers, or the underlying AI models.',
          'Use the service for any unlawful purpose.',
        ],
      },
      { type: 'p', text: 'We may suspend or terminate accounts that violate these Terms.' },
    ],
  },
  {
    id: 'your-content',
    title: 'Your Content',
    body: [
      {
        type: 'p',
        text: 'You retain ownership of the profile information and resumes you create using Resumaker. By using the service, you grant us the limited right to process that information (including sending it to our AI provider) solely to generate your resumes and operate the service, as described in our Privacy Policy.',
      },
    ],
  },
  {
    id: 'ip',
    title: 'Intellectual Property',
    body: [
      {
        type: 'p',
        text: 'Resumaker, its design, code, and branding are our property or licensed to us. These Terms do not grant you any rights to our intellectual property beyond using the extension as intended.',
      },
    ],
  },
  {
    id: 'third-party',
    title: 'Third-Party Services',
    body: [
      {
        type: 'p',
        text: 'Resumaker relies on third-party providers, including Google Firebase, Anthropic, and Stripe, to operate. We are not responsible for outages, errors, or changes originating from these providers.',
      },
    ],
  },
  {
    id: 'warranties',
    title: 'Disclaimer of Warranties',
    body: [
      {
        type: 'p',
        text: 'Resumaker is provided "as is" and "as available," without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy, or non-infringement. We do not warrant that the service will be uninterrupted, error-free, or that generated content will meet your expectations or those of any employer.',
      },
    ],
  },
  {
    id: 'liability',
    title: 'Limitation of Liability',
    body: [
      {
        type: 'p',
        text: 'To the fullest extent permitted by law, Resumaker and its operator are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including lost job opportunities, lost income, or reliance on AI-generated content. Our total liability for any claim relating to the service is limited to the amount you paid us in the three months prior to the claim.',
      },
    ],
  },
  {
    id: 'termination',
    title: 'Termination',
    body: [
      {
        type: 'p',
        text: 'You may stop using Resumaker and delete your account at any time. We may suspend or terminate your access if you violate these Terms or misuse the service. Upon termination, your right to use the service ends, though data retention follows our Privacy Policy.',
      },
    ],
  },
  {
    id: 'changes',
    title: 'Changes to These Terms',
    body: [
      {
        type: 'p',
        text: 'We may update these Terms as the product evolves. We will update the "Last updated" date above when we do. Continued use of the extension after changes constitutes acceptance of the updated Terms.',
      },
    ],
  },
  {
    id: 'contact',
    title: 'Contact',
    body: [
      {
        type: 'p',
        text: 'Questions about these Terms: mannyrosajr@gmail.com',
      },
    ],
  },
]

function Terms() {
  return (
    <div className="site-shell">
      <header className="site-header" aria-label="Main navigation">
        <a className="brand" href="/" aria-label="Resumaker home">
          <img className="brand-mark" src={resumakerIcon} alt="" />
          <span>Resumaker</span>
        </a>
        <a className="secondary-button legal-back" href="/">
          Back to site
        </a>
      </header>

      <main id="top">
        <section className="section legal-hero" aria-labelledby="legal-title">
          <p className="eyebrow">Legal</p>
          <h1 id="legal-title">Terms of Service</h1>
          <p className="legal-updated">Resumaker &middot; Last updated: July 9, 2026</p>
          <p className="legal-intro">
            These Terms of Service ("Terms") govern your use of Resumaker, a Chrome
            extension that generates tailored resumes using AI. By installing or using
            Resumaker, you agree to these Terms. If you do not agree, do not use the
            extension.
          </p>
        </section>

        <section className="section split-section legal-section" aria-label="Terms of Service sections">
          <div className="section-heading sticky-heading">
            <p className="eyebrow">On this page</p>
            <nav className="legal-nav" aria-label="Terms sections">
              {sections.map((section, i) => (
                <a href={`#${section.id}`} key={section.id}>
                  <span>{String(i + 1).padStart(2, '0')}</span>
                  {section.title}
                </a>
              ))}
            </nav>
          </div>

          <div className="legal-doc">
            {sections.map((section, i) => (
              <article className="legal-item" id={section.id} key={section.id}>
                <h2>
                  <span className="legal-number">{String(i + 1).padStart(2, '0')}</span>
                  {section.title}
                </h2>
                {section.body.map((block, blockIndex) =>
                  block.type === 'ul' ? (
                    <ul key={blockIndex}>
                      {block.items.map((item) => (
                        <li key={item}>{item}</li>
                      ))}
                    </ul>
                  ) : (
                    <p key={blockIndex}>{block.text}</p>
                  ),
                )}
              </article>
            ))}
          </div>
        </section>
      </main>

      <footer className="site-footer">
        <a className="brand" href="/" aria-label="Resumaker home">
          <img className="brand-mark" src={resumakerIcon} alt="" />
          <span>Resumaker</span>
        </a>
        <p>Tailored one-page resumes from the job posting you are viewing.</p>
        <div className="footer-links">
          <a href="mailto:contact@resumaker.app">Contact</a>
          <a href="/privacy">Privacy</a>
          <a href="/terms">Terms</a>
        </div>
      </footer>
    </div>
  )
}

export default Terms
